name: small workflow

on:
  push:
    branches:
      - master

jobs:
  test:
  # This will run the tests for each Python version
    name: Run Python Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout specific version
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          python -c "import mavenn"
          pytest -v --cov-report term-missing --cov=mavenn
